task 12
sergeylihodeevzelenyuk/hillelFrontEndPro pull request #3
Opened 2021-09-03 11:16 UTC by sergeylihodeevzelenyuk

2021-09-03 12:25 UTC, vladimirkr requested changes

2021-09-03 12:25 UTC, vladimirkr commented on Task-12/script.js
> +        input.placeholder = errorMassage;
Если хочешь показать сообщение то это нужно сделать не с помощью плейсхолдера а с помощью нового блока, например добавь div в html с текстом ошибки под инпутом по умолчанию с  display: none и показывай его.

2021-09-03 12:25 UTC, vladimirkr commented on Task-12/script.js
> +    if (input.value) {
добавь здесь проверку: 
```javascript
input.classList.remove("todo-input__error");

if (!input.value) {
  input.classList.add("todo-input__error");
  return;
}
```

2021-09-03 12:25 UTC, vladimirkr commented on Task-12/script.js
> +function activateInput() {
переименуй функцию в addToDoItem или addMessage т.е. действие которое происходит когда выполняется функция

2021-09-03 12:25 UTC, vladimirkr commented on Task-12/script.js
> +document.addEventListener("keydown", function (event) {
у тебя два одинаковых листенера, объедини их в один

2021-09-05 09:36 UTC, sergeylihodeevzelenyuk commented on Task-12/script.js
> +    if (input.value) {
А у меня же эта часть ( input.classList.add("todo-input__error");) выполняется как else к условию на 11 строке: 
if (input.value), то есть в любом случае только когда !input.value
Или лучше не использовать else? А еще раз прописать if и условие?

2021-09-05 09:36 UTC, sergeylihodeevzelenyuk commented on Task-12/script.js
> +document.addEventListener("keydown", function (event) {
Не совсем понял как их объединить, они же все-таки не совсем одинаковые, 
один отслеживает события по документу, а первый по инпуту: 

input.addEventListener("keydown", function (event) {

document.addEventListener("keydown", function (event) {

2021-09-06 07:35 UTC, vladimirkr commented on Task-12/script.js
> +document.addEventListener("keydown", function (event) {
Перенесите всю внутрянку из двух листенеров в один

2021-09-06 09:07 UTC, vladimirkr approved these changes

2021-09-06 09:07 UTC, vladimirkr commented on Task-12/script.js
> +    }
Если у вас будет еще с десяток классов с ошибками для каждого элемента, например вы добавите еще пару инпутов то код очень разрастется, ошибки нужно убирать вначале как я написал. можно вынести в отдельную функцию clearErrors()

2021-09-08 11:27 UTC, merged